import React from 'react';

// News — most recent first. Trimmed to the last two years.
export const NEWS = [
  ['2026', <span>Thesis summary "<i>Trustworthy AI-Assisted Programming</i>" published in <b>Proceedings of AAAI 2026</b>.</span>],
  ['2026', <span>PhD conferred at <b>NTU Singapore</b> — research on code LLM security and program repair.</span>],
  ['2025', <span>Paper "<i>Defects4C</i>" accepted to <b>ASE 2025</b> — comprehensive C/C++ APR benchmark for LLMs.</span>],
  ['2025', <span>Paper "<i>Do Code Semantics Help?</i>" accepted to <b>EMNLP Findings 2025</b>.</span>],
  ['2024', <span>Paper "<i>RATCHET</i>" accepted to <b>ISSRE 2024</b>; "<i>AIGC Detectors on Code</i>" to <b>ASE 2024</b>.</span>],
  ['2024', <span>Paper "<i>FGVulDet</i>" (vulnerability detection) at <b>LCTES 2024</b>.</span>],
];

// Featured publications.
export const FEATURED_PUBS = [
  {
    thumb: "AAAI'26",
    figure: 'trustworthy',
    title: 'Trustworthy AI-Assisted Programming: Detection and Repair of Unreliable Code',
    authors: <><b>Wang J.</b></>,
    venue: 'AAAI', year: '2026',
    badges: [
      { label: 'pdf', href: 'https://ojs.aaai.org/index.php/AAAI/article/view/42174' },
      { label: 'doi', href: 'https://doi.org/10.1609/aaai.v40i48.42174' },
    ],
    note: 'THESIS SUMMARY',
  },
  {
    thumb: "ASE'25",
    figure: 'defects4c',
    title: 'Defects4C: Benchmarking Large Language Model Repair Capability with C/C++ Bugs',
    authors: <><b>Wang J.</b>, Xie X., Hu Q., Liu S., Yu J., Kong J., Li Y.</>,
    venue: 'ASE', year: '2025',
    badges: [
      { label: 'pdf', href: 'https://arxiv.org/abs/2510.11059' },
      { label: 'code', href: 'https://github.com/defects4c/defects4c' },
    ],
    note: 'FEATURED',
  },
  {
    thumb: "EMNLP'25",
    figure: 'tracewise',
    title: 'Do Code Semantics Help? A Comprehensive Study on Execution Trace-Based Information for Code LLMs',
    authors: <><b>Wang J.</b>, Xie X., Hu Q., Liu S., Li Y.</>,
    venue: 'EMNLP FINDINGS', year: '2025',
    badges: [
      { label: 'pdf', href: 'https://aclanthology.org/2025.findings-emnlp.548/' },
      { label: 'arxiv', href: 'https://arxiv.org/abs/2509.11686' },
      { label: 'poster', href: 'https://github.com/jianwang-ntu/tracewise_probing/blob/main/emnlp_trace_poster.pdf' },
    ],
  },
  {
    thumb: "ASE'24",
    figure: 'aigcdet',
    title: 'An Empirical Study to Evaluate AIGC Detectors on Code Content',
    authors: <><b>Wang J.</b>, Liu S., Xie X., Li Y.</>,
    venue: 'ASE', year: '2024',
    badges: [
      { label: 'pdf', href: 'https://dl.acm.org/doi/10.1145/3691620.3695468' },
      { label: 'slides', href: 'https://liyiweb.com/files/Wang2024AES.slides.pdf' },
      { label: 'site', href: 'https://sites.google.com/view/nlccd' },
    ],
  },
];

export const ALL_PUBS = [
  { id: 'C6', figure: 'trustworthy', year: 2026, kind: 'conference',
    title: 'Trustworthy AI-Assisted Programming: Detection and Repair of Unreliable Code',
    authors: <><b>Wang J.</b></>,
    venue: 'AAAI',
    badges: [
      { label: 'pdf', href: 'https://ojs.aaai.org/index.php/AAAI/article/view/42174' },
      { label: 'doi', href: 'https://doi.org/10.1609/aaai.v40i48.42174' },
    ],
    note: 'THESIS SUMMARY' },
  { id: 'C5', figure: 'defects4c', year: 2025, kind: 'conference',
    title: 'Defects4C: Benchmarking Large Language Model Repair Capability with C/C++ Bugs',
    authors: <><b>Wang J.</b>, Xie X., Hu Q., Liu S., Yu J., Kong J., Li Y.</>,
    venue: 'ASE',
    badges: [
      { label: 'pdf', href: 'https://arxiv.org/abs/2510.11059' },
      { label: 'code', href: 'https://github.com/defects4c/defects4c' },
    ],
    note: 'FEATURED' },
  { id: 'C4', figure: 'tracewise', year: 2025, kind: 'conference',
    title: 'Do Code Semantics Help? A Comprehensive Study on Execution Trace-Based Information for Code Large Language Models',
    authors: <><b>Wang J.</b>, Xie X., Hu Q., Liu S., Li Y.</>,
    venue: 'EMNLP FINDINGS',
    badges: [
      { label: 'pdf', href: 'https://aclanthology.org/2025.findings-emnlp.548/' },
      { label: 'arxiv', href: 'https://arxiv.org/abs/2509.11686' },
      { label: 'poster', href: 'https://github.com/jianwang-ntu/tracewise_probing/blob/main/emnlp_trace_poster.pdf' },
    ] },
  { id: 'C3', figure: 'ratchet', year: 2024, kind: 'conference',
    title: 'RATCHET: Retrieval Augmented Transformer for Program Repair',
    authors: <><b>Wang J.</b>, Liu S., Xie X., Siow J. K., Liu K., Li Y.</>,
    venue: 'ISSRE',
    badges: [{ label: 'pdf', href: '/data/issre_RATCHET.pdf' }] },
  { id: 'C2', figure: 'aigcdet', year: 2024, kind: 'conference',
    title: 'An Empirical Study to Evaluate AIGC Detectors on Code Content',
    authors: <><b>Wang J.</b>, Liu S., Xie X., Li Y.</>,
    venue: 'ASE',
    badges: [
      { label: 'pdf', href: 'https://dl.acm.org/doi/10.1145/3691620.3695468' },
      { label: 'slides', href: 'https://liyiweb.com/files/Wang2024AES.slides.pdf' },
      { label: 'site', href: 'https://sites.google.com/view/nlccd' },
    ] },
  { id: 'C1', figure: 'fgvuldet', year: 2024, kind: 'conference',
    title: 'Enhancing Code Vulnerability Detection via Vulnerability-Preserving Data Augmentation',
    authors: <>Liu S., Ma W., <b>Wang J.</b>, Xie X., Feng R., Liu Y.</>,
    venue: 'LCTES',
    badges: [{ label: 'arxiv', href: 'https://arxiv.org/abs/2404.09599' }] },
  { id: 'J2', figure: 'faire', year: 2023, kind: 'journal',
    title: 'Faire: Repairing Fairness of Neural Networks via Neuron Condition Synthesis',
    authors: <>Li T., Xie X., <b>Wang J.</b>, Guo Q., Liu A., Ma L., Liu Y.</>,
    venue: 'ACM TOSEM',
    badges: [{ label: 'pdf', href: 'https://dl.acm.org/doi/10.1145/3617168' }] },
  { id: 'J1', year: 2022, kind: 'journal',
    title: 'NPC: Neuron Path Coverage via Characterizing Decision Logic of Deep Neural Networks',
    authors: <>Xie X., Li T., <b>Wang J.</b>, Ma L., Guo Q., Juefei-Xu F., Liu Y.</>,
    venue: 'ACM TOSEM',
    badges: [{ label: 'pdf', href: 'https://dl.acm.org/doi/10.1145/3490489' }] },
  { id: 'C0', figure: 'rnnrepair', year: 2021, kind: 'conference',
    title: 'Automatic RNN Repair via Model-based Analysis',
    authors: <>Xie X., Guo W., Ma L., Le W., <b>Wang J.</b>, Zhou L., Liu Y., Xing X.</>,
    venue: 'ICML',
    badges: [
      { label: 'pdf', href: 'http://proceedings.mlr.press/v139/xie21b/xie21b.pdf' },
      { label: 'page', href: 'http://proceedings.mlr.press/v139/xie21b.html' },
    ] },
  { id: 'P2', figure: 'abba', year: 2020, kind: 'conference',
    title: 'Watch out! Motion is Blurring the Vision of Your Deep Neural Networks',
    authors: <>Guo Q., Juefei-Xu F., Xie X., Ma L., <b>Wang J.</b>, Yu B., Feng W., Liu Y.</>,
    venue: 'NeurIPS',
    badges: [
      { label: 'pdf', href: '/data/felix_neurips20_abba.pdf' },
      { label: 'arxiv', href: 'http://arxiv.org/abs/2002.03500' },
    ] },
  { id: 'P1', figure: 'fakespotter', year: 2020, kind: 'conference',
    title: 'FakeSpotter: A Simple yet Robust Baseline for Spotting AI-Synthesized Fake Faces',
    authors: <>Wang R., Juefei-Xu F., Ma L., Xie X., Huang Y., <b>Wang J.</b>, Liu Y.</>,
    venue: 'IJCAI',
    badges: [
      { label: 'pdf', href: '/data/felix_ijcai20_fakespotter.pdf' },
      { label: 'arxiv', href: 'http://arxiv.org/abs/1909.06122' },
      { label: 'media', href: 'https://syncedreview.com/2019/09/23/ai-vs-ai-fakespotter-studies-neurons-to-bust-deepfakes/' },
    ] },
];

// Work — newest first. PhD start aligned with bio (Aug 2021).
export const WORK = [
  { year: 'Aug 2023 — now', role: 'Research Engineer Manager',
    where: 'Singapore Management University · Code Intelligence & LLM Security',
    kind: 'RESEARCH',
    what: <>Building <b>Defects4C</b> (350 expert-validated C/C++ bugs distilled from 38M+ commits) and <b>tracewise probing</b>; evaluating 24 SOTA LLMs across single-round and conversation-based repair; analysing parallel vs. sequential scaling under compute budgets.</>,
    stack: ['Python', 'PyTorch', 'SFT/PEFT', 'LLMs', 'C/C++', 'Benchmarking'],
    transfer: 'Production-scale system design from 58.com translates directly to building reproducible large-scale benchmarks. The reliability instincts are the same; the substrate is now LLM evaluation pipelines.',
    papers: ["ASE '25 (Defects4C)", "EMNLP '25 (Code Semantics)"],
    pivot: true },
  { year: 'Aug 2021 — Aug 2023', role: 'PhD Student',
    where: 'Nanyang Technological University · Deep Learning & LLM Security',
    kind: 'RESEARCH',
    what: <>Large-scale empirical study of 13 AIGC detectors on 2M+ code samples. Built <b>RATCHET</b> — retrieval-augmented APR with BiLSTM fault localisation. Developed neuro-symbolic methods for DL testing: <b>NPC</b> path coverage and <b>Faire</b> fairness repair. Core team in the AI Singapore deepfake challenge.</>,
    stack: ['PyTorch', 'GNN/GGNN', 'Transformers', 'Symbolic Methods', 'Adversarial Robustness'],
    transfer: 'The CNN/GAN work at Xiaomi gave me the model-internals lens that NPC and Faire later operationalised — neuron-level coverage and condition synthesis are the same intuition under a research budget.',
    papers: ["ASE '24 (AIGC)", "ISSRE '24 (RATCHET)", "LCTES '24 (FGVulDet)", "TOSEM '23 (Faire)", "TOSEM '22 (NPC)", "ICML '21", "NeurIPS '20", "IJCAI '20"],
    pivot: true },
  { year: 'Dec 2019 — Aug 2021', role: 'Research Assistant',
    where: 'Nanyang Technological University · Deep Learning Security',
    kind: 'RESEARCH',
    what: <>Pre-PhD research bridge — neural-network testing, robustness analysis, and the early infrastructure that became NPC and the AIGC-detector study.</>,
    stack: ['PyTorch', 'Adversarial Robustness', 'DL Testing'],
    transfer: 'Built the experimental scaffolding that the later PhD work ran on top of.',
    papers: [] },
  { year: '2017 — 2019', role: 'Research Scientist · Xiaomi AI Lab',
    where: 'Xiaomi Group · AI Lab · Beijing',
    kind: 'INDUSTRY',
    what: <>Contributed to Xiaomi's deep-learning framework and large-scale vision/algorithm services. Worked on portrait segmentation pipelines (GCN / GAN / CNN) and the GPU→on-device flow: training (CUDA / PyTorch) → quantisation / pruning → ONNX/IR conversion → inference on Hexagon DSP / Kirin NPU. Cascaded multi-mask approach for natural-scene blur.</>,
    stack: ['CUDA', 'PyTorch', 'ONNX', 'Quantisation', 'Hexagon DSP', 'Kirin NPU'],
    transfer: 'Shipping models end-to-end through quantisation and on-device inference forced me to take ML seriously as software. That discipline is what I now bring to APR benchmarks and trace-based fine-tuning.',
    papers: [] },
  { year: '2011 — 2017', role: 'Backend Engineer · 58.com',
    where: '58 Inc. · Mobile Web / Backend Infrastructure · Beijing',
    kind: 'INDUSTRY',
    what: <>Designed and shipped a high-performance asynchronous web framework that handles <b>100M+ daily requests</b> in production, and a user-profiling and behavior-analytics platform. Owned reliability, latency, and scalability at production scale.</>,
    stack: ['Backend', 'Async Web Framework', 'Middleware/API', 'Mobile Web', 'On-call'],
    transfer: 'Six years owning latency and reliability at scale. That muscle is what makes me build benchmarks that other people can actually reproduce.',
    papers: [] },
  { year: '2011', role: 'Data Engineering Intern',
    where: 'Baidu, Inc. · Beijing',
    kind: 'INDUSTRY',
    what: <>Contributed to large-scale data pipelines; first hands-on production data-engineering experience.</>,
    stack: ['Data Engineering', 'Pipelines'],
    transfer: 'First exposure to production-scale data handling — the prerequisite for any later large-scale empirical study.',
    papers: [] },
];
